# Generated by Django 4.2.5 on 2023-10-03 03:28

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DonBanHang',
            fields=[
                ('ma_don_hang', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('ngay_ban', models.DateTimeField(default=datetime.datetime.now)),
                ('tong_tien', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('cancelled', models.BooleanField(default=False)),
                ('confirmed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='HangHoa',
            fields=[
                ('ma_hang_hoa', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('ten_hang_hoa', models.CharField(max_length=100)),
                ('nhom_hang_hoa', models.CharField(max_length=100)),
                ('image', models.ImageField(default=None, upload_to='media/', verbose_name='Label')),
                ('gia', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='KhachHang',
            fields=[
                ('ma_khach_hang', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('ten_khach_hang', models.CharField(max_length=100)),
                ('dia_chi', models.CharField(max_length=100)),
                ('so_dien_thoai', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('cancelled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong', models.IntegerField()),
                ('DonBanHang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DonBanHang', to='home.donbanhang')),
                ('hang_hoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.hanghoa')),
            ],
        ),
        migrations.AddField(
            model_name='donbanhang',
            name='hang_hoa',
            field=models.ManyToManyField(through='home.Order', to='home.hanghoa'),
        ),
        migrations.AddField(
            model_name='donbanhang',
            name='khach_hang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='KhachHang', to='home.khachhang'),
        ),
        migrations.AddField(
            model_name='donbanhang',
            name='nguoi_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
